### ISSUE TITLE
Make Olib Browser not cooking, if not using.

### ISSUE THREAD

**Issue by joshuahhn** [function-store/FunctionStore_tools#35]
Olib Browser seems like whatever will keep cooking even not open/use.

![image](https://github.com/function-store/FunctionStore_tools/assets/18750955/43a21eeb-b6f1-44bd-8e81-affea61475ed)

It almost 50% FunctionStore_tools cook time, sometime also make frame drop randomly.

AMD Ryzen 9 5900X 12-Core Processor
64.0 GB RAM
RTX4090

**Comment by function-store** [comment]
hey thanks for the report. It'll not always cook in the next release, however I was seeing lower numbers and haven't experienced drops myself. Hope the next release will run smoother for you (soon)
