### ISSUE TITLE
Create Null Hotkey?

### ISSUE THREAD

**Issue by rosofo** [function-store/FunctionStore_tools#39]
If it's in the docs I didn't spot it, is there a way to quickly create and connect a null to an op?

**Comment by function-store** [comment]
Hey there is already in stock TD: Alt+N

I have it bound to my mouse personally :)

**Comment by rosofo** [comment]
Mind blown

**Comment by eisenbruch** [comment]
Alt+N no longer works since I have installed Function Store Tools. Did I break something?
