### ISSUE TITLE
Navbar Mods Hover constantly flickers on Mac

### ISSUE THREAD

**Issue by cdellasilva** [function-store/FunctionStore_tools#40]
Hovering over individual element in Nav bar causes constant loop.  The shortcut popup flashes on/off and it closes right click menu immediately.  The Mac window buttons also visibly flicker.  Appears to be popup and TD fighting for window active state.

Running TD 2023.11880, on an M1 Max w/ Sonoma 14.5

Loaded 11600 and confirmed it works correctly there.

**Comment by function-store** [comment]
Thanks I recently got back my test Mac and can reproduce it. Looking for the cause!

**Comment by function-store** [comment]
There's an attempted fix in the latest release. However it's not 100% the same fluidity as on Windows. I've gotta hit up derivative with this issue I guess!
