### ISSUE TITLE
Suggestion: auto-externalize CustomParHelpers & NoNode for type hinting

### ISSUE THREAD

**Issue by rosofo** [function-store/FunctionStore_tools#47]
Whenever I create my first extension in a project I invariably externalize the helpers. VSCode can pick up the types that way. Maybe worth just doing it on extension creation?

**Comment by function-store** [comment]
It's supposed to deploy its stubs (type hints and definitions) to TD python
environment. In your VSCode select TD's python.exe as your interpreter!

**Comment by rosofo** [comment]
oh that makes sense. I've been in the habit of pointing it at a venv created per project but as I started using td_pip recently, I suppose there's less of a need to do that.
