### ISSUE TITLE
Recursion warning in CustomParHelper

### ISSUE THREAD

**Issue by rosofo** [function-store/FunctionStore_tools#48]
https://github.com/function-store/FunctionStore_tools/blob/72174c3e7a00736ce95a209d2d930c1b382d9221/scripts/QuickExt/templates/ExtUtils/CustomParHelper/CustomParHelper.py#L114C1-L115C1

TD reports a recursion warning on extension init at this line. Commenting it out removes it. Might not cause any problems but is distracting

**Comment by function-store** [comment]
hmm yes... I've just noticed that. Problem is, without that line sometimes the reference do not eval or update to that class attribute used by the Script OPs needed by the framework (referring to the parent essentially), unless it is made dependable.

As you say, it's probably just annoying...

**Comment by function-store** [comment]
managed to fix it https://github.com/function-store/FunctionStore_tools/commit/4a9ad97f511c5bae247a96f79186bf7f2d7bd500
